# Generated by Django 2.2.7 on 2019-11-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='machine_groups',
            field=models.ManyToManyField(null=True, to='machines.MachineGroup'),
        ),
        migrations.AlterField(
            model_name='machinegroup',
            name='machines',
            field=models.ManyToManyField(null=True, to='machines.Machine'),
        ),
    ]
