# Generated by Django 2.2.7 on 2019-11-23 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_auto_20191122_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='ssh_key_in_vault',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HostVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(null=True)),
                ('is_in_vault', models.BooleanField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Machine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(null=True)),
                ('is_in_vault', models.BooleanField()),
                ('machine_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.MachineGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
