# Generated by Django 2.2.7 on 2019-11-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_auto_20191123_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupvars',
            name='vault_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hostvars',
            name='vault_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
