# Generated by Django 2.2.7 on 2019-11-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_auto_20191123_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='use_consul',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
