# Generated by Django 2.2.7 on 2019-11-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_auto_20191126_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
