# Generated by Django 2.2.7 on 2019-11-26 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_auto_20191126_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='ssh_key_in_vault',
            new_name='use_vault_for_credentials',
        ),
    ]
