version: '3'
services:
  vault:
    image: vault:latest
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=lol_bananas_12
    ports:
      - "8200:8200"

  consul_1:
    image: consul:latest
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: agent -server -ui -data-dir=/consul/data -bootstrap -retry-join consul_2 -retry-join consul_3
    volumes:
    - "$PWD/consul/data_1:/consul/data"
    ports:
      - "8300:8300"

  consul_2:
    image: consul:latest
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: consul agent -server -data-dir=/consul/data -retry-join=consul_1 -retry-join consul_3
    volumes:
    - "$PWD/consul/data_2:/consul/data"

  consul_3:
    image: consul:latest
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: consul agent -server -data-dir=/consul/data -retry-join=consul_1 -retry-join consul_2
    volumes:
    - "$PWD/consul/data_3:/consul/data"

  consul-agent:
    image: consul:latest
    hostname: agent1
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: agent -dev -join=consul_1
    volumes:
      - "./consul_default_confs:/consul/config"

  ssh-agent:
    build:
      context: ./consul_default_confs/
      dockerfile: $PWD/DevContainers/Dockerfile.consul_ssh
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_JOIN_ADDR=consul
    volumes:
      - "./consul_default_confs:/consul/config"